name: hawkeye_travel_app
description: Boilerplate by Dimas Ibnu Malik github.com/dimas-ibnu.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  provider: ^4.1.2
  shared_preferences: ^0.5.7+2
  material_design_icons_flutter: ^4.0.5345
  google_fonts: ^1.1.0
  flutter_html: ^1.0.0
  url_launcher: ^5.7.2
  shimmer: ^1.1.1
  image_picker: ^0.6.7+11
  carousel_slider: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    #Logo
    - assets/images/logo.png

    #Placeholder Images
    - assets/images/placeholder/no-image.png

    #Images - Illustrations
    - assets/images/person.jpg
    - assets/images/banner.png
    - assets/images/forest.png

    #Images - Categories
    - assets/images/categories/double_tree.png
    - assets/images/categories/earth.png
    - assets/images/categories/love.png
    - assets/images/categories/pinus.png

    #Iconly
    - assets/icons/2 User.svg                
    - assets/icons/3 User.svg                
    - assets/icons/Activity.svg               
    - assets/icons/Add User.svg              
    - assets/icons/Arrow - Down 2.svg        
    - assets/icons/Arrow - Down 3.svg        
    - assets/icons/Arrow - Down Circle.svg   
    - assets/icons/Arrow - Down Square.svg   
    - assets/icons/Arrow - Down.svg          
    - assets/icons/Arrow - Left 2.svg        
    - assets/icons/Arrow - Left 3.svg        
    - assets/icons/Arrow - Left Circle.svg   
    - assets/icons/Arrow - Left Square.svg   
    - assets/icons/Arrow - Left.svg          
    - assets/icons/Arrow - Right 2.svg       
    - assets/icons/Arrow - Right 3.svg       
    - assets/icons/Arrow - Right Circle.svg  
    - assets/icons/Arrow - Right Square.svg  
    - assets/icons/Arrow - Right.svg         
    - assets/icons/Arrow - Up 2.svg          
    - assets/icons/Arrow - Up 3.svg     
    - assets/icons/Arrow - Up Circle.svg
    - assets/icons/Arrow - Up Square.svg
    - assets/icons/Arrow - Up.svg       
    - assets/icons/Bag 2.svg            
    - assets/icons/Bag.svg               
    - assets/icons/Bookmark.svg          
    - assets/icons/Buy.svg               
    - assets/icons/Calendar.svg          
    - assets/icons/Call Missed.svg      
    - assets/icons/Call Silent.svg      
    - assets/icons/Call.svg              
    - assets/icons/Calling.svg           
    - assets/icons/Camera.svg            
    - assets/icons/Category.svg          
    - assets/icons/Chart.svg             
    - assets/icons/Chat.svg              
    - assets/icons/Close Square.svg     
    - assets/icons/Danger.svg            
    - assets/icons/Delete.svg
    - assets/icons/Discount.svg    
    - assets/icons/Discovery.svg    
    - assets/icons/Document.svg     
    - assets/icons/Download.svg     
    - assets/icons/Edit Square.svg 
    - assets/icons/Edit.svg         
    - assets/icons/Filter 2.svg    
    - assets/icons/Filter.svg       
    - assets/icons/Folder.svg       
    - assets/icons/Game.svg         
    - assets/icons/Graph.svg        
    - assets/icons/Heart.svg        
    - assets/icons/Hide.svg         
    - assets/icons/Home.svg         
    - assets/icons/Image 2.svg     
    - assets/icons/Image.svg        
    - assets/icons/Info Circle.svg 
    - assets/icons/Info Square.svg 
    - assets/icons/Location.svg     
    - assets/icons/Lock.svg
    - assets/icons/Login.svg
    - assets/icons/Logout.svg
    - assets/icons/Message.svg
    - assets/icons/More Circle.svg
    - assets/icons/More Square.svg
    - assets/icons/Notification.svg
    - assets/icons/Paper Download.svg
    - assets/icons/Paper Fail.svg
    - assets/icons/Paper Negative.svg
    - assets/icons/Paper Plus.svg
    - assets/icons/Paper Upload.svg
    - assets/icons/Paper.svg
    - assets/icons/Password.svg
    - assets/icons/Play.svg
    - assets/icons/Plus.svg
    - assets/icons/Profile.svg
    - assets/icons/Scan.svg
    - assets/icons/Search.svg
    - assets/icons/Send.svg
    - assets/icons/Setting.svg
    - assets/icons/Shield Done.svg
    - assets/icons/Shield Fail.svg
    - assets/icons/Show.svg
    - assets/icons/Star.svg
    - assets/icons/Swap.svg
    - assets/icons/Tick Square.svg
    - assets/icons/Ticket Star.svg
    - assets/icons/Ticket.svg
    - assets/icons/Time Circle.svg
    - assets/icons/Time Square.svg
    - assets/icons/Unlock.svg
    - assets/icons/Upload.svg
    - assets/icons/Video.svg
    - assets/icons/Voice 2.svg
    - assets/icons/Voice.svg
    - assets/icons/Volume Down.svg
    - assets/icons/Volume Off.svg
    - assets/icons/Volume Up.svg
    - assets/icons/Wallet.svg
    - assets/icons/Work.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
